apiVersion: apiextensions.crossplane.io/v1alpha1
kind: FunctionIO
observed:
  composite:
    resource:
      apiVersion: demo.upbound.io/v1alpha1
      kind: XKubernetesCluster
      metadata:
        name: xcluster
      spec:
        teams:
          - environments:
              - name: dev
                path: ./dev
              - name: staging
                path: ./staging
              - name: production
                path: ./production
            name: team-blue
            repository: https://github.com/upbound-demo/team-blue
  resources:
    - name: compositeClusterEKS
      connectionDetails: null
      resource:
        apiVersion: demo.upbound.io/v1alpha1
        kind: XEKS
        metadata:
          name: app-dev-1-6hctt-d6j6m
        spec:
          nameForProviderConfigs: app-dev-1-6hctt
        status:
          subnetIds:
            - subnet-1234567890abcdef0
desired:
  composite:
    connectionDetails: null
    resource:
      apiVersion: demo.upbound.io/v1alpha1
      kind: XKubernetesCluster
      metadata:
        name: xcluster
      spec:
        teams:
          - environments:
              - name: dev
                path: ./dev
              - name: staging
                path: ./staging
              - name: production
                path: ./production
            name: team-blue
            repository: https://github.com/upbound-demo/team-blue
  resources:
    - name: compositeClusterEKS
      resource:
        apiVersion: demo.upbound.io/v1alpha1
        kind: XEKS
        metadata:
          name: app-dev-1-6hctt-d6j6m
        spec:
          nameForProviderConfigs: app-dev-1-6hctt
        status:
          subnetIds:
            - subnet-1234567890abcdef0
    - name: gitrepository-team-blue
      resource:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          creationTimestamp: null
        spec:
          forProvider:
            manifest:
              apiVersion: source.toolkit.fluxcd.io/v1
              kind: GitRepository
              metadata:
                creationTimestamp: null
                name: team-blue
                namespace: flux-system
              spec:
                interval: 1m0s
                ref:
                  branch: main
                url: https://github.com/upbound-demo/team-blue
              status: {}
          providerConfigRef:
            name: app-dev-1-6hctt
        status:
          atProvider:
            manifest: null
    - name: kustomization-team-blue-dev
      resource:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          creationTimestamp: null
        spec:
          forProvider:
            manifest:
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                creationTimestamp: null
                name: team-blue-dev
                namespace: flux-system
              spec:
                interval: 1m0s
                path: ./dev
                prune: false
                sourceRef:
                  kind: GitRepository
                  name: team-blue
                  namespace: flux-system
              status: {}
          providerConfigRef:
            name: app-dev-1-6hctt
        status:
          atProvider:
            manifest: null
    - name: kustomization-team-blue-staging
      resource:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          creationTimestamp: null
        spec:
          forProvider:
            manifest:
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                creationTimestamp: null
                name: team-blue-staging
                namespace: flux-system
              spec:
                interval: 1m0s
                path: ./staging
                prune: false
                sourceRef:
                  kind: GitRepository
                  name: team-blue
                  namespace: flux-system
              status: {}
          providerConfigRef:
            name: app-dev-1-6hctt
        status:
          atProvider:
            manifest: null
    - name: kustomization-team-blue-production
      resource:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          creationTimestamp: null
        spec:
          forProvider:
            manifest:
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                creationTimestamp: null
                name: team-blue-production
                namespace: flux-system
              spec:
                interval: 1m0s
                path: ./production
                prune: false
                sourceRef:
                  kind: GitRepository
                  name: team-blue
                  namespace: flux-system
              status: {}
          providerConfigRef:
            name: app-dev-1-6hctt
        status:
          atProvider:
            manifest: null