apiVersion: apiextensions.crossplane.io/v1alpha1
kind: FunctionIO
observed:
  composite:
    resource:
      apiVersion: demo.upbound.io/v1alpha1
      kind: XKubernetesCluster
      metadata:
        name: xcluster
      spec:
        teams:
          - environments:
              - name: dev
                path: ./dev
              - name: staging
                path: ./staging
              - name: production
                path: ./production
            name: team-blue
            repository: https://github.com/upbound-demo/team-blue
  resources:
    - name: compositeClusterEKS
      resource:
        apiVersion: demo.upbound.io/v1alpha1
        kind: XEKS
        metadata:
          name: app-dev-1-6hctt-d6j6m
        spec:
          nameForProviderConfigs: app-dev-1-6hctt
        status:
          subnetIds:
            - subnet-1234567890abcdef0
desired:
  composite:
    resource:
      apiVersion: demo.upbound.io/v1alpha1
      kind: XKubernetesCluster
      metadata:
        name: xcluster
      spec:
        teams:
          - environments:
              - name: dev
                path: ./dev
              - name: staging
                path: ./staging
              - name: production
                path: ./production
            name: team-blue
            repository: https://github.com/upbound-demo/team-blue
  resources:
    - name: compositeClusterEKS
      resource:
        apiVersion: demo.upbound.io/v1alpha1
        kind: XEKS
        metadata:
          name: app-dev-1-6hctt-d6j6m
        spec:
          nameForProviderConfigs: app-dev-1-6hctt
        status:
          subnetIds:
            - subnet-1234567890abcdef0